#Guessing the random number generated by the computer
import random

def guess(x):
    random_number = random.randint(1, x) #random.randint returns a random integer from a to b
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_number:
            print("Sorry, guess again. Too low.")
        elif guess > random_number:
            print("Sorry, guess again. Too high.")
    else: #code to execute when the loops ends naturally i.e. the while condition becomes false
        print(f"Yay, congrats. You have guessed the number {random_number} correctly!!")
        
guess(10)

#Get the computer to guess our secret number
def secret(x):
    low = 1
    high = x 
    feedback = ""
    while feedback != "c": #random.randint will show an error when both low and high are the same number\
        # and you still tell the computer to adjust its bounds by inputting "h" or "l"
        computer_guess = random.randint(low, high)
        feedback = input(f"Is {computer_guess} too high (H), too low (L), or correct (C)?? ").lower()
        if feedback == "h":
            high = computer_guess - 1
        elif feedback == "l":
            low = computer_guess + 1
    print(f'Bingo, I guessed "{computer_guess}" correctly. Never underestimate your computer again.')

secret(10)
