#Guessing the random number generated by the computer
import random

def guess(x):
    random_number = random.randint(1, x) #random.randint returns a random integer from a to b
    guess = 0
    while guess != random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess < random_number:
            print("Sorry, guess again. Too low.")
        elif guess > random_number:
            print("Sorry, guess again. Too high.")
    else: #code to execute when the loops ends naturally i.e. the while condition becomes false
        print(f"Yay, congrats. You have guessed the number {random_number} correctly!!")
        
guess(10)


        